# Generated by Django 6.0.7 on 2026-07-13 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recensioni', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provvedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('avvertimento', 'Avvertimento'), ('ban', 'Ban (sospensione account)')], max_length=20)),
                ('motivazione', models.TextField(help_text='Motivazione del provvedimento, es. riferimento alla segnalazione che lo ha originato.')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('amministratore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provvedimenti_emessi', to=settings.AUTH_USER_MODEL)),
                ('recensione_collegata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provvedimenti_generati', to='recensioni.recensione')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provvedimenti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Provvedimenti',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
