# Generated by Django 6.0.7 on 2026-07-13 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escursione', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('segnalata', models.BooleanField(default=False)),
                ('risposta_guida', models.TextField(blank=True, default='', verbose_name='Risposta della Guida')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_scritte', to=settings.AUTH_USER_MODEL)),
                ('escursione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='escursione.escursione')),
            ],
            options={
                'verbose_name_plural': 'Recensioni',
                'ordering': ['-data_creazione'],
                'unique_together': {('escursione', 'autore')},
            },
        ),
    ]
