# Generated by Django 6.0.7 on 2026-07-13 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipaggiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Equipaggiamenti',
            },
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Zone Geografiche',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Escursione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('punto_di_ritrovo', models.CharField(max_length=100)),
                ('latitudine', models.FloatField(blank=True, null=True)),
                ('longitudine', models.FloatField(blank=True, null=True)),
                ('descrizione', models.TextField()),
                ('dislivello', models.PositiveIntegerField()),
                ('difficolta', models.CharField(choices=[('T', 'Turistico'), ('E', 'Escursionistico'), ('EE', 'Esperti')], max_length=2)),
                ('foto_copertina', models.ImageField(upload_to='escursione/copertine/')),
                ('approvata', models.BooleanField(default=False)),
                ('equipaggiamento', models.ManyToManyField(blank=True, related_name='escursioni', to='escursione.equipaggiamento')),
                ('guida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escursioni_create', to=settings.AUTH_USER_MODEL)),
                ('zona_geografica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escursioni', to='escursione.zonageografica')),
            ],
            options={
                'verbose_name_plural': 'Escursioni',
            },
        ),
        migrations.CreateModel(
            name='FotoGalleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='escursione/galleria/')),
                ('escursione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria', to='escursione.escursione')),
            ],
            options={
                'verbose_name_plural': 'Foto Galleria',
            },
        ),
        migrations.CreateModel(
            name='Uscita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ritrovo', models.DateTimeField()),
                ('posti_totali', models.PositiveIntegerField()),
                ('posti_occupati', models.PositiveIntegerField(default=0)),
                ('escursione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uscite_programmate', to='escursione.escursione')),
            ],
            options={
                'verbose_name_plural': 'Uscite Programmate',
            },
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prenotazione', models.DateTimeField(auto_now_add=True)),
                ('stato', models.CharField(choices=[('confermata', 'Confermata'), ('attesa', "In lista d'attesa")], default='confermata', max_length=20)),
                ('escursionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to=settings.AUTH_USER_MODEL)),
                ('uscita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='escursione.uscita')),
            ],
            options={
                'verbose_name_plural': 'Prenotazioni',
                'unique_together': {('escursionista', 'uscita')},
            },
        ),
    ]
